const lessons=[{title:"The Hero's Point of View",description:"Identify how point of view changes what a reader knows and feels.",question:"A story is told by a character who only knows what she personally sees and hears. Which point of view is this?",choices:["First person","Third-person limited","Third-person omniscient","Second person"],answer:0,skill:"Reading comprehension",explain:"First person uses a narrator who is a character in the story and speaks from their own perspective."},{title:"Inference: Read Between the Lines",description:"Use clues from a scene to make a strong inference.",question:"A character keeps checking the clock, rereads a message three times, and quietly packs a notebook. What is the strongest inference?",choices:["They are preparing for something important.","They dislike notebooks.","They have forgotten how to tell time.","They are definitely going to sleep."],answer:0,skill:"Inference & evidence",explain:"The repeated actions are clues that the character is preparing for an important event."},{title:"Word Quest: Context Clues",description:"Use surrounding words to figure out an unfamiliar word.",question:"The ancient map was so fragile that everyone handled it carefully. What does fragile most likely mean?",choices:["Easily damaged","Very colorful","Extremely large","Hard to find"],answer:0,skill:"Vocabulary",explain:"The clue “handled it carefully” suggests the map could be easily damaged."},{title:"Grammar Forge: Sentence Craft",description:"Choose the sentence with the clearest construction.",question:"Which sentence uses a comma correctly?",choices:["After the quest, the heroes returned home.","After, the quest the heroes returned home.","After the quest the, heroes returned home.","After the quest the heroes, returned home."],answer:0,skill:"Grammar",explain:"A comma separates the introductory phrase from the main clause."}];
let current=0;let data=JSON.parse(localStorage.getItem('ishuQuestData')||'{"xp":120,"completed":2,"correct":10,"answered":12,"sessions":4}');
const $=id=>document.getElementById(id);const save=()=>localStorage.setItem('ishuQuestData',JSON.stringify(data));
function accuracy(){return data.answered?Math.round(data.correct/data.answered*100):0}
function skillHTML(){const skills=[['Reading comprehension',82],['Vocabulary',90],['Grammar',78],['Writing',84]];return skills.map(([n,v])=>`<div class="progress-row"><span>${n}</span><strong>${v}%</strong></div><div class="bar"><i style="width:${v}%"></i></div>`).join('')}
function render(){const l=lessons[current];$('lessonTitle').textContent=l.title;$('lessonDescription').textContent=l.description;$('lessonArea').innerHTML=`<div class="question">${l.question}</div><div class="choices">${l.choices.map((c,i)=>`<button class="choice" data-i="${i}">${c}</button>`).join('')}</div><div id="feedback" class="feedback"></div>`;document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',answer));$('xp').textContent=data.xp;$('lessons').textContent=data.completed;$('accuracy').textContent=accuracy()+'%';$('studentSkills').innerHTML=skillHTML();}
function answer(e){const buttons=[...document.querySelectorAll('.choice')];buttons.forEach(b=>b.disabled=true);const selected=Number(e.currentTarget.dataset.i);const l=lessons[current];const correct=selected===l.answer;e.currentTarget.classList.add(correct?'correct':'wrong');if(!correct)buttons[l.answer].classList.add('correct');data.answered++;if(correct){data.correct++;data.xp+=40;data.completed++;}save();$('feedback').textContent=correct?`✨ Correct! +40 XP — ${l.explain}`:`Not quite. ${l.explain}`;renderStats();setTimeout(()=>{current=(current+1)%lessons.length;render();},1600)}
function renderStats(){$('xp').textContent=data.xp;$('lessons').textContent=data.completed;$('accuracy').textContent=accuracy()+'%';$('studentSkills').innerHTML=skillHTML()}
function show(view){const parent=view==='parent';$('studentView').classList.toggle('hidden',parent);$('parentView').classList.toggle('hidden',!parent);$('studentBtn').classList.toggle('active',!parent);$('parentBtn').classList.toggle('active',parent);if(parent){$('parentScore').textContent=accuracy()+'%';$('pSessions').textContent=data.sessions;$('pQuestions').textContent=data.answered;$('pXp').textContent=data.xp;$('parentSkills').innerHTML=skillHTML()}}
$('continueBtn').addEventListener('click',()=>document.querySelector('.lesson-area').scrollIntoView({behavior:'smooth',block:'center'}));$('studentBtn').addEventListener('click',()=>show('student'));$('parentBtn').addEventListener('click',()=>show('parent'));$('parentStudentBtn').addEventListener('click',()=>show('student'));render();